openapi: 3.0.0
info:
  title: Data Plane
  version: '2.0'
  description: 'https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md'
  license:
    name: Apache 2.0
servers: []
paths:
  /v2/health/live:
    get:
      summary: Server Live
      responses:
        '200':
          description: OK
      operationId: get-v2-health-live
      description: The “server live” API indicates if the inference server is able to receive and respond to metadata and inference requests. The “server live” API can be used directly to implement the Kubernetes livenessProbe.
  /v2/health/ready:
    get:
      summary: Server Ready
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-v2-health-ready
      description: The “server ready” health API indicates if all the models are ready for inferencing. The “server ready” health API can be used directly to implement the Kubernetes readinessProbe.
  '/v2/models/{model_name}/versions/{model_version}/ready':
    parameters:
      - schema:
          type: string
        name: model_name
        in: path
        required: true
      - schema:
          type: string
        name: model_version
        in: path
        required: true
    get:
      summary: Model Ready
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-v2-models-$-modelName-versions-$-modelVersion-ready
      description: The “model ready” health API indicates if a specific model is ready for inferencing. The model name and (optionally) version must be available in the URL. If a version is not provided the server may choose a version based on its own policies.
  /v2:
    get:
      summary: Server Metadata
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataServerResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataServerErrorResponse'
      operationId: get-v2
      description: 'The server metadata endpoint provides information about the server. A server metadata request is made with an HTTP GET to a server metadata endpoint. In the corresponding response the HTTP body contains the [Server Metadata Response JSON Object](#MetadataServerResponse) or the [Server Metadata Response JSON Error Object](#MetadataServerErrorResponse).'
  '/v2/models/{model_name}/versions/{model_version}':
    parameters:
      - schema:
          type: string
        name: model_name
        in: path
        required: true
      - schema:
          type: string
        name: model_version
        in: path
        required: true
    get:
      summary: Model Metadata
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataModelResponse'
      operationId: get-v2-models-$-modelName-versions-$-modelVersion
      description: 'The per-model metadata endpoint provides information about a model. A model metadata request is made with an HTTP GET to a model metadata endpoint. In the corresponding response the HTTP body contains the [Model Metadata Response JSON Object](#MetadataModelResponse) or the [Model Metadata Response JSON Error Object](#MetadataModelErrorResponse). The model name and (optionally) version must be available in the URL. If a version is not provided the server may choose a version based on its own policies or return an error.'
  '/v2/models/{model_name}/versions/{model_version}/infer':
    parameters:
      - schema:
          type: string
        name: model_name
        in: path
        required: true
      - schema:
          type: string
        name: model_version
        in: path
        required: true
    post:
      summary: Inference
      operationId: post-v2-models-$-MODEL_NAME-versions-$-MODEL_VERSION-infer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InferenceRequest'
      description: 'An inference request is made with an HTTP POST to an inference endpoint. In the request the HTTP body contains the [Inference Request JSON Object](#inference-request-json-object). In the corresponding response the HTTP body contains the [Inference Response JSON Object](#inference-response-json-object) or [Inference Response JSON Error Object](#inference-response-json-error-object). See [Inference Request Examples](#inference-request-examples) for some example HTTP/REST requests and responses.'
components:
  schemas:
    MetadataServerResponse:
      title: MetadataServerResponse
      type: object
      description: ''
      x-examples: {}
      properties:
        name:
          type: string
        version:
          type: string
        extensions:
          type: array
          items:
            type: string
      required:
        - name
        - version
        - extensions
    MetadataServerErrorResponse:
      title: MetadataServerErrorResponse
      type: object
      properties:
        error:
          type: string
      required:
        - error
    MetadataModelResponse:
      title: MetadataModelResponse
      type: object
      properties:
        name:
          type: string
        versions:
          type: array
          items:
            type: string
        platform:
          type: string
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/MetadataTensor'
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/MetadataTensor'
        parameters:
          $ref: '#/components/schemas/Parameters'
      required:
        - name
        - platform
    MetadataTensor:
      title: MetadataTensor
      type: object
      properties:
        name:
          type: string
        datatype:
          type: string
        shape:
          type: array
          items:
            type: integer
        parameters:
          $ref: '#/components/schemas/Parameters'
      required:
        - name
        - datatype
        - shape
    MetadataModelErrorResponse:
      title: MetadataModelErrorResponse
      type: object
      properties:
        error:
          type: string
      required:
        - error
    InferenceRequest:
      title: InferenceRequest
      type: object
      x-examples:
        Example 1:
          id: '42'
          inputs:
            - name: input0
              shape:
                - 2
                - 2
              datatype: UINT32
              data:
                - 1
                - 2
                - 3
                - 4
            - name: input1
              shape:
                - 3
              datatype: BOOL
              data:
                - true
          outputs:
            - name: output0
        Example 2:
          id: '42'
          outputs:
            - name: output0
              shape:
                - 3
                - 2
              datatype: FP32
              data:
                - 1
                - 1.1
                - 2
                - 2.1
                - 3
                - 3.1
      properties:
        id:
          type: string
        parameters:
          $ref: '#/components/schemas/Parameters'
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/RequestInput'
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/RequestOutput'
      required:
        - inputs
    Parameters:
      type: object
      title: Parameters
      x-examples: {}
      additionalProperties: true
      properties:
        content_type:
          type: string
        headers:
          type: object
    RequestInput:
      title: RequestInput
      type: object
      properties:
        name:
          type: string
        shape:
          type: array
          items:
            type: integer
        datatype:
          type: string
        parameters:
          $ref: '#/components/schemas/Parameters'
        data:
          $ref: '#/components/schemas/TensorData'
      required:
        - name
        - shape
        - datatype
        - data
    TensorData:
      title: TensorData
    RequestOutput:
      title: RequestOutput
      type: object
      properties:
        name:
          type: string
        parameters:
          $ref: '#/components/schemas/Parameters'
      required:
        - name
    ResponseOutput:
      title: ResponseOutput
      type: object
      properties:
        name:
          type: string
        shape:
          type: array
          items:
            type: integer
        datatype:
          type: string
        parameters:
          $ref: '#/components/schemas/Parameters'
        data:
          $ref: '#/components/schemas/TensorData'
      required:
        - name
        - shape
        - datatype
        - data
    InferenceResponse:
      title: InferenceResponse
      type: object
      properties:
        model_name:
          type: string
        model_version:
          type: string
        id:
          type: string
        parameters:
          $ref: '#/components/schemas/Parameters'
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/ResponseOutput'
      required:
        - model_name
        - outputs
    InferenceErrorResponse:
      title:  InferenceErrorResponse
      type: object
      properties:
        error:
          type: string
